DROP DATABASE IF EXISTS DBDELEGACIA;

CREATE DATABASE DBDELEGACIA;

USE DBDELEGACIA;

CREATE TABLE CRIME (
	IDCRIME INT NOT NULL,
	DESCRICAO VARCHAR(255),
	RUA VARCHAR(100),
	NUMERO INT,
	COMPLEMENTO VARCHAR(255),
	BAIRRO VARCHAR(100),
	CEP VARCHAR(8),
	CIDADE VARCHAR(100),
	ESTADO CHAR(2)
);

CREATE TABLE CRIMINOSO(
  RUA VARCHAR(100),
  NUMERO INT,
  COMPLEMENTO VARCHAR(255),
  BAIRRO VARCHAR(100),
  CEP CHAR(8),
  CIDADE VARCHAR(100),
  ESTADO CHAR(2),
  DTNASCIMENTO DATE,
  TELEFONE VARCHAR(15)
);

CREATE TABLE OCORRENCIA (
	IDOCORRENCIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DT_OCORRENCIA DATE
);

CREATE TABLE ITEM_OCORRENCIA (
	IDITEM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDOCORRENCIA INT NOT NULL,
	DESCRICAO VARCHAR (100),
	CONSTRAINT FK_ITEM_OCORRENCIA_OCORRENCIA FOREIGN KEY (IDOCORRENCIA) REFERENCES OCORRENCIA(IDOCORRENCIA)
);

CREATE TABLE VITIMA (
  RUA VARCHAR(100),
  NUMERO INT,
  COMPLEMENTO VARCHAR(255),
  BAIRRO VARCHAR(100),
  CEP VARCHAR(8),
  CIDADE VARCHAR(100),
  ESTADO CHAR(2),
  DTNASCIMENTO DATE
);

CREATE TABLE COMETE(
	IDCRIME INT NOT NULL,
	IDCRIMINOSO INT NOT NULL
);

CREATE TABLE ATACA (
	OBSERVACAO CHAR(1)
);

CREATE TABLE SOFRE (
	IDCRIME INT NOT NULL,
	IDVITIMA INT NOT NULL
);

CREATE TABLE ARMA (
	IDARMA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(110)
);

CREATE TABLE USADA (
	IDARMA INT NOT NULL,
	IDCRIME INT NOT NULL
);


#Tirando as tabelas inúteis
DROP TABLE ITEM_OCORRENCIA;
DROP TABLE OCORRENCIA;
#----------------------------
#Arrumando tabela CRIME
DROP TABLE CRIME;
CREATE TABLE CRIME (
	IDCRIME INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DESCRICAO VARCHAR(200),
    DTCRIME DATETIME
);
DESCRIBE CRIME;
#----------------------------
#Arrumando tabela CRIMINOSO
DROP TABLE CRIMINOSO;
CREATE TABLE CRIMINOSO(
	IDCRIMINOSO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(45),
    DTNASCIMENTO DATE
);
DESCRIBE CRIMINOSO;
#----------------------------
#Arrumando tabela COMETE
ALTER TABLE COMETE
ADD FOREIGN KEY(IDCRIME) REFERENCES CRIME(IDCRIME);
ALTER TABLE COMETE
ADD FOREIGN KEY(IDCRIMINOSO) REFERENCES CRIMINOSO(IDCRIMINOSO);
DESCRIBE COMETE;
#----------------------------
#Arrumando tabela VITIMA
DROP TABLE VITIMA;
CREATE TABLE VITIMA(
	IDVITIMA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(45),
    DTNASCIMENTO DATE
);
DESCRIBE VITIMA;
#----------------------------
#Arrumando tabela ataca
DROP TABLE ATACA;
CREATE TABLE ATACA(
	IDCRIMINOSO INT NOT NULL,
	IDVITIMA INT NOT NULL,
    FOREIGN KEY(IDCRIMINOSO) REFERENCES CRIMINOSO(IDCRIMINOSO),
    FOREIGN KEY(IDVITIMA) REFERENCES VITIMA(IDVITIMA)
);
DESCRIBE ATACA;
#----------------------------
#Arrumando tabela SOFRE
ALTER TABLE SOFRE
ADD FOREIGN KEY(IDCRIME) REFERENCES CRIME(IDCRIME);
ALTER TABLE SOFRE
ADD FOREIGN KEY(IDVITIMA) REFERENCES VITIMA(IDVITIMA);
DESCRIBE SOFRE;
#----------------------------
#Arrumando tabela ARMA
ALTER TABLE ARMA
DROP COLUMN MARCA;
ALTER TABLE ARMA
ADD COLUMN DESCRICAO VARCHAR(45);
ALTER TABLE ARMA
ADD COLUMN TIPO ENUM("Tipo1", "Tipo2", "Tipo3", "Tipo4");
ALTER TABLE ARMA
ADD COLUMN IDENTIFICACAO VARCHAR(15);
DESCRIBE ARMA;
#----------------------------
#Arrumando tabela USADA
ALTER TABLE USADA
RENAME TO USAR;
ALTER TABLE USAR
ADD FOREIGN KEY(IDCRIME) REFERENCES CRIME(IDCRIME);
ALTER TABLE USAR
ADD FOREIGN KEY(IDARMA) REFERENCES ARMA(IDARMA);
DESCRIBE USAR;
#----------------------------